namespace ERSwapper;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    private void InitializeComponent()
    {
        System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
        pnlBottom = new Panel();
        lblStatus = new Label();
        progressBar = new ProgressBar();
        flowTools = new FlowLayoutPanel();
        btnResetAll = new Button();
        btnUnsupported = new Button();
        btnHistory = new Button();
        btnResetPreviews = new Button();
        btnSettings = new Button();
        btnExtract = new Button();
        btnApply = new Button();
        pnlCenter = new Panel();
        cardGallery = new CardPanel();
        lstItems = new ListView();
        pnlSearch = new Panel();
        cboBundle = new ComboBox();
        txtSearch = new TextBox();
        pnlCategories = new CardPanel();
        lstCategories = new ListBox();
        cardSide = new Panel();
        cardDetails = new CardPanel();
        lblDetails = new Label();
        cardPreview = new CardPanel();
        picPreview = new PictureBox();
        pnlBottom.SuspendLayout();
        flowTools.SuspendLayout();
        pnlCenter.SuspendLayout();
        cardGallery.SuspendLayout();
        pnlSearch.SuspendLayout();
        pnlCategories.SuspendLayout();
        cardSide.SuspendLayout();
        cardDetails.SuspendLayout();
        cardPreview.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)picPreview).BeginInit();
        SuspendLayout();
        pnlBottom.Controls.Add(lblStatus);
        pnlBottom.Controls.Add(progressBar);
        pnlBottom.Controls.Add(flowTools);
        pnlBottom.Controls.Add(btnExtract);
        pnlBottom.Controls.Add(btnApply);
        pnlBottom.Dock = DockStyle.Bottom;
        pnlBottom.Location = new Point(14, 664);
        pnlBottom.Name = "pnlBottom";
        pnlBottom.Size = new Size(1126, 140);
        pnlBottom.TabIndex = 4;
        lblStatus.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        lblStatus.AutoEllipsis = true;
        lblStatus.Location = new Point(14, 24);
        lblStatus.Name = "lblStatus";
        lblStatus.Size = new Size(1098, 18);
        lblStatus.TabIndex = 1;
        lblStatus.Text = "Ready.";
        progressBar.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        progressBar.Location = new Point(14, 8);
        progressBar.Name = "progressBar";
        progressBar.Size = new Size(1098, 10);
        progressBar.TabIndex = 0;
        flowTools.AutoSize = true;
        flowTools.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        flowTools.Controls.Add(btnResetAll);
        flowTools.Controls.Add(btnUnsupported);
        flowTools.Controls.Add(btnHistory);
        flowTools.Controls.Add(btnResetPreviews);
        flowTools.Controls.Add(btnSettings);
        flowTools.Location = new Point(14, 46);
        flowTools.Name = "flowTools";
        flowTools.Size = new Size(620, 44);
        flowTools.TabIndex = 2;
        flowTools.WrapContents = false;
        btnResetAll.Location = new Point(0, 4);
        btnResetAll.Margin = new Padding(0, 4, 8, 4);
        btnResetAll.Name = "btnResetAll";
        btnResetAll.Size = new Size(150, 36);
        btnResetAll.TabIndex = 0;
        btnResetAll.Text = "Reset All Swaps";
        btnResetAll.Click += btnResetAll_Click;
        btnUnsupported.Location = new Point(158, 4);
        btnUnsupported.Margin = new Padding(0, 4, 8, 4);
        btnUnsupported.Name = "btnUnsupported";
        btnUnsupported.Size = new Size(180, 36);
        btnUnsupported.TabIndex = 1;
        btnUnsupported.Text = "What cannot be swapped?";
        btnUnsupported.Click += btnUnsupported_Click;
        btnHistory.Location = new Point(346, 4);
        btnHistory.Margin = new Padding(0, 4, 8, 4);
        btnHistory.Name = "btnHistory";
        btnHistory.Size = new Size(120, 36);
        btnHistory.TabIndex = 2;
        btnHistory.Text = "Swap History";
        btnHistory.Click += btnHistory_Click;
        btnResetPreviews.Location = new Point(474, 4);
        btnResetPreviews.Margin = new Padding(0, 4, 8, 4);
        btnResetPreviews.Name = "btnResetPreviews";
        btnResetPreviews.Size = new Size(146, 36);
        btnResetPreviews.TabIndex = 3;
        btnResetPreviews.Text = "Rebuild Previews";
        btnResetPreviews.Click += btnResetPreviews_Click;

        btnSettings.Margin = new Padding(0, 4, 0, 4);
        btnSettings.Name = "btnSettings";
        btnSettings.Size = new Size(100, 36);
        btnSettings.TabIndex = 4;
        btnSettings.Text = "Settings";
        btnSettings.Click += btnSettings_Click;
        btnExtract.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnExtract.Location = new Point(648, 96);
        btnExtract.Name = "btnExtract";
        btnExtract.Size = new Size(230, 36);
        btnExtract.TabIndex = 3;
        btnExtract.Text = "Extract && Open in Editor";
        btnExtract.Click += btnExtract_Click;
        btnApply.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnApply.Enabled = false;
        btnApply.Location = new Point(888, 96);
        btnApply.Name = "btnApply";
        btnApply.Size = new Size(224, 36);
        btnApply.TabIndex = 4;
        btnApply.Text = "Apply Edited Texture";
        btnApply.Click += btnApply_Click;
        pnlCenter.Controls.Add(cardGallery);
        pnlCenter.Controls.Add(pnlSearch);
        pnlCenter.Dock = DockStyle.Fill;
        pnlCenter.Location = new Point(196, 0);
        pnlCenter.Name = "pnlCenter";
        pnlCenter.Padding = new Padding(0, 10, 0, 8);
        pnlCenter.Size = new Size(604, 664);
        pnlCenter.TabIndex = 2;
        cardGallery.BackColor = Color.FromArgb(31, 31, 37);
        cardGallery.Controls.Add(lstItems);
        cardGallery.Dock = DockStyle.Fill;
        cardGallery.ForeColor = Color.FromArgb(232, 232, 237);
        cardGallery.Location = new Point(0, 52);
        cardGallery.Name = "cardGallery";
        cardGallery.Padding = new Padding(10, 32, 10, 10);
        cardGallery.Size = new Size(604, 604);
        cardGallery.TabIndex = 1;
        cardGallery.Title = "Items";
        lstItems.Dock = DockStyle.Fill;
        lstItems.Location = new Point(10, 32);
        lstItems.MultiSelect = false;
        lstItems.Name = "lstItems";
        lstItems.Size = new Size(584, 562);
        lstItems.TabIndex = 0;
        lstItems.UseCompatibleStateImageBehavior = false;
        lstItems.SelectedIndexChanged += lstItems_SelectedIndexChanged;
        lstItems.DoubleClick += lstItems_DoubleClick;
        pnlSearch.Controls.Add(cboBundle);
        pnlSearch.Controls.Add(txtSearch);
        pnlSearch.Dock = DockStyle.Top;
        pnlSearch.Location = new Point(0, 10);
        pnlSearch.Name = "pnlSearch";
        pnlSearch.Size = new Size(604, 42);
        pnlSearch.TabIndex = 0;
        cboBundle.DropDownStyle = ComboBoxStyle.DropDownList;
        cboBundle.FormattingEnabled = true;
        cboBundle.Location = new Point(0, 6);
        cboBundle.Name = "cboBundle";
        cboBundle.Size = new Size(230, 23);
        cboBundle.TabIndex = 0;
        cboBundle.SelectedIndexChanged += cboBundle_SelectedIndexChanged;
        txtSearch.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtSearch.Location = new Point(236, 6);
        txtSearch.Name = "txtSearch";
        txtSearch.PlaceholderText = "Search items…";
        txtSearch.Size = new Size(368, 23);
        txtSearch.TabIndex = 1;
        txtSearch.TextChanged += txtSearch_TextChanged;
        pnlCategories.BackColor = Color.FromArgb(31, 31, 37);
        pnlCategories.Controls.Add(lstCategories);
        pnlCategories.Dock = DockStyle.Left;
        pnlCategories.ForeColor = Color.FromArgb(232, 232, 237);
        pnlCategories.Location = new Point(14, 0);
        pnlCategories.Name = "pnlCategories";
        pnlCategories.Padding = new Padding(8, 32, 8, 10);
        pnlCategories.Size = new Size(182, 664);
        pnlCategories.TabIndex = 1;
        pnlCategories.Title = "Categories";
        lstCategories.BorderStyle = BorderStyle.None;
        lstCategories.Dock = DockStyle.Fill;
        lstCategories.DrawMode = DrawMode.OwnerDrawFixed;
        lstCategories.IntegralHeight = false;
        lstCategories.ItemHeight = 34;
        lstCategories.Location = new Point(8, 32);
        lstCategories.Name = "lstCategories";
        lstCategories.Size = new Size(166, 622);
        lstCategories.TabIndex = 0;
        lstCategories.DrawItem += lstCategories_DrawItem;
        lstCategories.SelectedIndexChanged += lstCategories_SelectedIndexChanged;
        cardSide.Controls.Add(cardDetails);
        cardSide.Controls.Add(cardPreview);
        cardSide.Dock = DockStyle.Right;
        cardSide.Location = new Point(800, 0);
        cardSide.Name = "cardSide";
        cardSide.Padding = new Padding(14, 10, 14, 8);
        cardSide.Size = new Size(340, 664);
        cardSide.TabIndex = 3;
        cardDetails.BackColor = Color.FromArgb(31, 31, 37);
        cardDetails.Controls.Add(lblDetails);
        cardDetails.Dock = DockStyle.Fill;
        cardDetails.ForeColor = Color.FromArgb(232, 232, 237);
        cardDetails.Location = new Point(14, 310);
        cardDetails.Name = "cardDetails";
        cardDetails.Padding = new Padding(10, 32, 10, 10);
        cardDetails.Size = new Size(312, 346);
        cardDetails.TabIndex = 1;
        cardDetails.Title = "Selected item";
        lblDetails.Dock = DockStyle.Fill;
        lblDetails.Location = new Point(10, 32);
        lblDetails.Name = "lblDetails";
        lblDetails.Size = new Size(292, 304);
        lblDetails.TabIndex = 0;
        lblDetails.Text = "Pick an item from the gallery.";
        cardPreview.BackColor = Color.FromArgb(31, 31, 37);
        cardPreview.Controls.Add(picPreview);
        cardPreview.Dock = DockStyle.Top;
        cardPreview.ForeColor = Color.FromArgb(232, 232, 237);
        cardPreview.Location = new Point(14, 10);
        cardPreview.Name = "cardPreview";
        cardPreview.Padding = new Padding(10, 32, 10, 10);
        cardPreview.Size = new Size(312, 300);
        cardPreview.TabIndex = 0;
        cardPreview.Title = "Preview";
        picPreview.Dock = DockStyle.Fill;
        picPreview.Location = new Point(10, 32);
        picPreview.Name = "picPreview";
        picPreview.Size = new Size(292, 258);
        picPreview.SizeMode = PictureBoxSizeMode.Zoom;
        picPreview.TabIndex = 0;
        picPreview.TabStop = false;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1140, 760);
        Controls.Add(pnlCenter);
        Controls.Add(cardSide);
        Controls.Add(pnlCategories);
        Controls.Add(pnlBottom);
        Icon = (Icon)resources.GetObject("$this.Icon");
        MinimumSize = new Size(1060, 700);
        Name = "MainForm";
        Padding = new Padding(14, 0, 0, 0);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "ER Swapper";
        pnlBottom.ResumeLayout(false);
        pnlBottom.PerformLayout();
        flowTools.ResumeLayout(false);
        pnlCenter.ResumeLayout(false);
        cardGallery.ResumeLayout(false);
        pnlSearch.ResumeLayout(false);
        pnlSearch.PerformLayout();
        pnlCategories.ResumeLayout(false);
        cardSide.ResumeLayout(false);
        cardDetails.ResumeLayout(false);
        cardPreview.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)picPreview).EndInit();
        ResumeLayout(false);
    }

    #endregion
    private System.Windows.Forms.Panel pnlBottom;
    private System.Windows.Forms.Label lblStatus;
    private System.Windows.Forms.ProgressBar progressBar;
    private System.Windows.Forms.Button btnResetAll;
    private System.Windows.Forms.Button btnUnsupported;
    private System.Windows.Forms.Button btnResetPreviews;
    private System.Windows.Forms.Button btnHistory;
    private System.Windows.Forms.Button btnSettings;
    private System.Windows.Forms.FlowLayoutPanel flowTools;
    private System.Windows.Forms.Button btnExtract;
    private System.Windows.Forms.Button btnApply;
    private System.Windows.Forms.Panel pnlCenter;
    private ERSwapper.Core.CardPanel cardGallery;
    private System.Windows.Forms.ListView lstItems;
    private System.Windows.Forms.Panel pnlSearch;
    private System.Windows.Forms.TextBox txtSearch;
    private System.Windows.Forms.ComboBox cboBundle;
    private ERSwapper.Core.CardPanel pnlCategories;
    private System.Windows.Forms.ListBox lstCategories;
    private System.Windows.Forms.Panel cardSide;
    private ERSwapper.Core.CardPanel cardPreview;
    private System.Windows.Forms.PictureBox picPreview;
    private ERSwapper.Core.CardPanel cardDetails;
    private System.Windows.Forms.Label lblDetails;
}
